GreenMobility/Areas/Admin/Controllers/AdminBicyclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GreenMobility.Models;
using PagedList.Core;
using GreenMobility.Helper;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;

namespace GreenMobility.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class AdminBicyclesController : Controller
    {
        private readonly GreenMobilityContext _context;
        private readonly INotyfService _notyf;
        public AdminBicyclesController(GreenMobilityContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        // GET: Admin/Bicycles
        public async Task<IActionResult> Index(int page = 1, int status = 0, string keyword = "")
        {
            var pageNumber = page;
            var pageSize = 20;

            IQueryable<Bicycle> bicycleQuery = _context.Bicycles
                .AsNoTracking()
                .Include(x => x.Parking)
                .Include(x => x.BicycleStatus)
                .Where(x => x.IsDeleted == false);

            if (!string.IsNullOrEmpty(keyword))
            {
                keyword = keyword.Trim().ToLower();
                bicycleQuery = bicycleQuery
                    .Where(x => x.BicycleName.ToLower().Contains(keyword)
                            || x.Parking.Address.Contains(keyword)
                            || x.Parking.ParkingName.Contains(keyword)
                            || x.LicensePlate.Contains(keyword));
            }
            if (status != 0)
            {
                bicycleQuery = bicycleQuery.Where(x => x.BicycleStatusId == status);
            }

            var lsBicycles = await bicycleQuery.ToListAsync();

            PagedList<Bicycle> models = new PagedList<Bicycle>(lsBicycles.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentStatus = status;
            ViewData["Status"] = new SelectList(_context.BicycleStatuses, "BicycleStatusId", "Description", status);
            ViewBag.Keyword = keyword;
            return View(models);
        }

        public IActionResult FilterAndSearch(int status = 0, string keyword = "")
        {
            var url = $"/Admin/AdminBicycles?status={status}&keyword={keyword}";
            if (status == 0 && string.IsNullOrEmpty(keyword))
            {
                url = "/Admin/AdminBicycles";
            }
            return Json(new { status = "success", redirectUrl = url });
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bicycles == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycles
                .Include(x => x.Parking)
                .Include(x => x.BicycleStatus)
                .FirstOrDefaultAsync(m => m.BicycleId == id && m.IsDeleted == false);
            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        public IActionResult Create()
        {
            ViewData["lsBaiDo"] = new SelectList(_context.Parkings.Where(p => p.IsDeleted == false), "ParkingId", "ParkingName");
            ViewData["lsTrangThai"] = new SelectList(_context.BicycleStatuses, "BicycleStatusId", "Description");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BicycleId,BicycleName,Description,ParkingId,LicensePlate,Photo,BicycleStatusId,RentalPrice,IsDeleted")] Bicycle bicycle, IFormFile? fPhoto)
        {
            if (string.IsNullOrWhiteSpace(bicycle.BicycleName))
                ModelState.AddModelError("BicycleName", "Tên xe không được để trống");

            if (string.IsNullOrWhiteSpace(bicycle.LicensePlate))
                ModelState.AddModelError("LicensePlate", "Biển số không được để trống");

            if (bicycle.ParkingId == 0)
                ModelState.AddModelError("ParkingId", "Vui lòng chọn một bãi xe");

            if (bicycle.RentalPrice <= 0 || bicycle.RentalPrice.ToString() == "")
                ModelState.AddModelError("RentalPrice", "Vui lòng nhập giá thuê hợp lệ");

            if (bicycle.BicycleStatusId == 0)
                ModelState.AddModelError("BicycleStatusId", "Vui lòng chọn một trạng thái");

            if (LicensePlateExists(bicycle.LicensePlate))
            {
                ModelState.AddModelError("LicensePlate", "Biển số xe đã tồn tại");
                return View(bicycle);
            }
            if (ModelState.IsValid)
            {
                bicycle.BicycleName = Utilities.ToTitleCase(bicycle.BicycleName);
                bicycle.LicensePlate = Utilities.ToTitleCase(bicycle.LicensePlate);

                if (fPhoto != null)
                {
                    string extension = Path.GetExtension(fPhoto.FileName);
                    string image = Utilities.SEOUrl(bicycle.LicensePlate) + extension;
                    bicycle.Photo = await Utilities.UploadFile(fPhoto, @"bicycles", image.ToLower());
                }

                if (string.IsNullOrEmpty(bicycle.Photo)) bicycle.Photo = "default.jpg";

                bicycle.Alias = Utilities.SEOUrl(bicycle.LicensePlate);
                bicycle.DateModified = DateTime.Now;
                bicycle.DateCreated = DateTime.Now;
                bicycle.IsDeleted = false;

                _context.Add(bicycle);
                await _context.SaveChangesAsync();
                _notyf.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }
            _notyf.Error("Tạo mới thất bại, vui lòng kiểm tra lại thông tin");
            ViewData["lsBaiDo"] = new SelectList(_context.Parkings.Where(p => p.IsDeleted == false), "ParkingId", "ParkingName");
            ViewData["lsTrangThai"] = new SelectList(_context.BicycleStatuses, "BicycleStatusId", "Description");
            return View(bicycle);

        }

        // GET: Admin/Bicycles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bicycles == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycles.FirstOrDefaultAsync(p => p.BicycleId == id && p.IsDeleted == false);
            if (bicycle == null)
            {
                return NotFound();
            }
            ViewData["lsBaiDo"] = new SelectList(_context.Parkings.Where(p => p.IsDeleted == false), "ParkingId", "ParkingName");
            ViewData["lsTrangThai"] = new SelectList(_context.BicycleStatuses, "BicycleStatusId", "Description");
            return View(bicycle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BicycleId,BicycleName,Description,ParkingId,LicensePlate,Photo,BicycleStatusId,RentalPrice,IsDeleted")] Bicycle bicycle, IFormFile? fPhoto)
        {
            if (id != bicycle.BicycleId)
            {
                return NotFound();
            }

            if (string.IsNullOrWhiteSpace(bicycle.BicycleName))
                ModelState.AddModelError("BicycleName", "Tên xe không được để trống");

            if (string.IsNullOrWhiteSpace(bicycle.LicensePlate))
                ModelState.AddModelError("LicensePlate", "Biển số không được để trống");

            if (bicycle.ParkingId == 0)
                ModelState.AddModelError("ParkingId", "Vui lòng chọn một bãi xe");

            if (bicycle.RentalPrice <= 0)
                ModelState.AddModelError("RentalPrice", "Vui lòng nhập giá thuê hợp lệ");


            if (bicycle.BicycleStatusId == 0)
                ModelState.AddModelError("BicycleStatusId", "Vui lòng chọn một trạng thái");

            if (LicensePlateExistsExceptCurrent(bicycle.LicensePlate, id))
                ModelState.AddModelError("LicensePlate", "Biển số xe đã tồn tại");

            if (ModelState.IsValid)
            {
                try
                {
                        bicycle.BicycleName = Utilities.ToTitleCase(bicycle.BicycleName);
                        bicycle.LicensePlate = Utilities.ToTitleCase(bicycle.LicensePlate);

                        if (fPhoto != null)
                        {
                            string extension = Path.GetExtension(fPhoto.FileName);
                            string image = Utilities.SEOUrl(bicycle.LicensePlate) + extension;
                            bicycle.Photo = await Utilities.UploadFile(fPhoto, @"bicycles", image.ToLower());
                        }

                        if (string.IsNullOrEmpty(bicycle.Photo)) bicycle.Photo = "default.jpg";

                        bicycle.Alias = Utilities.SEOUrl(bicycle.LicensePlate);
                        bicycle.DateModified = DateTime.Now;

                        _context.Update(bicycle);
                        await _context.SaveChangesAsync();
                        _notyf.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BicycleExists(bicycle.BicycleId))
                    {
                        _notyf.Warning("Có lỗi xảy ra");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            _notyf.Error("Chỉnh sửa thất bại, vui lòng kiểm tra lại thông tin");
            ViewData["lsBaiDo"] = new SelectList(_context.Parkings.Where(p => p.IsDeleted == false), "ParkingId", "ParkingName");

GreenMobility/Areas/Admin/Views/AdminBicycles/Create.cshtml
@model GreenMobility.Models.Bicycle

@{
    ViewData["Title"] = "Thêm mới xe đạp";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles {
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
<form asp-controller="AdminBicycles" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters">
        <div class="row align-items-md-center">
            <div class="col-md-8">
                <h2 class="header-title">Quản lý xe đạp</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                        <a asp-area="Admin" asp-controller="AdminBicycles" asp-action="Index" class="breadcrumb-item">Danh sách xe đạp</a>
                        <span class="breadcrumb-item active">Thêm mới xe đạp</span>
                    </nav>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-md-right">
                    <div>
                        <button type="submit" class="btn btn-primary mr-1">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        <a asp-area="Admin" asp-controller="AdminBicycles" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-content m-t-15">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Thông tin xe đạp</h4>
            </div>
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="img-fluid m-h-10 m-r-15" style="height: 80px; width: 120px">
                        <img id="avatarPreview" src="~/images/bicycles/default.jpg" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                    </div>

                    <div class="m-l-20 m-r-20">
                        <h5 class="m-b-5 font-size-18">Ảnh đại diện</h5>
                        <p class="opacity-07 font-size-13 m-b-0">
                            Đề xuất: <br>
                            Ảnh chi tiết
                        </p>
                    </div>
                    <div>
                        <label for="Photo" class="btn btn-tone btn-primary">Chọn ảnh</label>
                        <input type="file" name="fPhoto" asp-for="Photo" onchange="previewAvatar(event)" style="display: none;">
                    </div>
                </div>

                <hr class="m-v-25">
                <div class="form-group">
                    <label class="font-weight-semibold" for="BicycleName">Tên xe đạp</label>
                    <input type="text" class="form-control" asp-for="BicycleName" autofocus>
                    @Html.ValidationMessage("BicycleName", new { @style = "color:#f00" })
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="LicensePlate">Biển số</label>
                        <input type="text" class="form-control" asp-for="LicensePlate">
                        @Html.ValidationMessage("LicensePlate", new { @style = "color:#f00" })
                    </div>
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="RentalPrice">Giá thuê</label>
                        <input type="number" class="form-control" asp-for="RentalPrice">
                        @Html.ValidationMessage("RentalPrice", new { @style = "color:#f00" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="ParkingId">Bãi xe</label>
                        <select class="custom-select" asp-for="ParkingId" style="min-width: 200px;" asp-items="ViewBag.lsBaiDo">
                            <option value="0" selected>Chọn bãi xe</option>
                        </select>
                        @Html.ValidationMessage("ParkingId", new { @style = "color:#f00" })
                    </div>
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="BicycleStatusId">Trạng thái</label>
                        <select class="custom-select" asp-for="BicycleStatusId" style="min-width: 200px;" asp-items="ViewBag.lsTrangThai">
                            <option value="0" selected>Chọn trạng thái</option>
                        </select>
                        @Html.ValidationMessage("BicycleStatusId", new { @style = "color:#f00" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Mô tả</h4>
            </div>
            <div class="card-body">
                <textarea class="summernote" asp-for="Description"></textarea>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
            });
        });
        function previewAvatar(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('avatarPreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}

GreenMobility/Areas/Admin/Views/AdminBicycles/Details.cshtml
@model GreenMobility.Models.Bicycle

@{
    ViewData["Title"] = "Thông tin xe đạp";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header no-gutters">
    <div class="row align-items-md-center">
        <div class="col-md-7">
            <h2 class="header-title">Quản lý xe đạp</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                    <a asp-area="Admin" asp-controller="AdminBicycles" asp-action="Index" class="breadcrumb-item">Danh sách xe đạp</a>
                    <span class="breadcrumb-item active">Thông tin xe đạp</span>
                </nav>
            </div>
        </div>
        <div class="col-md-5">
            <div class="text-md-right d-flex justify-content-end">
                <a class="btn btn-primary btn-tone mr-2" asp-area="Admin" asp-controller="Adminbicycles" asp-action="Edit" asp-route-id="@Model.BicycleId">Sửa đổi</a>
                <form id="deleteForm" method="post" asp-action="Delete" asp-route-id="@Model.BicycleId" class="mr-2">
                    <button type="submit" class="btn btn-danger btn-tone">Xóa</button>
                </form>
                <a asp-area="Admin" asp-controller="AdminBicycles" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
            </div>
        </div>
    </div>
</div>
<div class="tab-content m-t-15">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Thông tin xe đạp</h4>
        </div>
        <div class="card-body">
            <div class="media align-items-center">
                <div class="img-fluid m-h-10 m-r-15" style="height: 80px; width: 120px">
                    <img id="avatarPreview" src="~/images/bicycles/@Model.Photo" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                </div>

                <div class="m-l-20 m-r-20">
                    <h5 class="m-b-5 font-size-18">@Model.BicycleName - @Model.LicensePlate</h5>
                </div>
            </div>
            <hr class="m-v-25">
            <div class="table-responsive">
                <table class="product-info-table m-t-20">
                    <tbody>
                        <tr>
                            <td>Tên xe đạp:</td>
                            <td class="text-dark font-weight-semibold">@Model.BicycleName</td>
                        </tr>
                        <tr>
                            <td>Biển số:</td>
                            <td>@Model.LicensePlate</td>
                        </tr>
                        <tr>
                            <td>Alias:</td>
                            <td>@Model.Alias</td>
                        </tr>
                        <tr>
                            <td>Giá thuê:</td>
                            <td>@Model.RentalPrice</td>
                        </tr>
                        <tr>
                            <td>Trạng thái:</td>
                            <td>@Model.BicycleStatus?.Description</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Thông tin mô tả</h4>
        </div>
        <div class="card-body">
            @Html.Raw(Model.Description)
        </div>
    </div>
</div>
@section scripts {
    <script>
        document.getElementById("deleteForm").addEventListener("submit", function (event) {
            event.preventDefault();

            if (confirm("Bạn có chắc chắn muốn xóa xe đạp này?")) {
                this.submit();
            }
        });
    </script>
}

GreenMobility/Areas/Admin/Views/AdminBicycles/Edit.cshtml
@model GreenMobility.Models.Bicycle

@{
    ViewData["Title"] = "Chỉnh sửa xe đạp";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles {
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
<form asp-controller="AdminBicycles" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="BicycleId" />
    <input type="hidden" asp-for="Photo" />
    <input type="hidden" asp-for="DateCreated" />
    <input type="hidden" asp-for="IsDeleted" />
    <div class="page-header no-gutters">
        <div class="row align-items-md-center">
            <div class="col-md-8">
                <h2 class="header-title">Quản lý xe đạp</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                        <a asp-area="Admin" asp-controller="AdminBicycles" asp-action="Index" class="breadcrumb-item">Danh sách xe đạp</a>
                        <span class="breadcrumb-item active">Chỉnh sửa xe đạp</span>
                    </nav>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-md-right">
                    <div>
                        <button type="submit" class="btn btn-primary mr-1">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        <a asp-area="Admin" asp-controller="AdminBicycles" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-content m-t-15">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Thông tin xe đạp</h4>
            </div>
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="img-fluid m-h-10 m-r-15" style="height: 80px; width: 120px">
                        <img id="avatarPreview" src="~/images/bicycles/@Model.Photo" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                    </div>

                    <div class="m-l-20 m-r-20">
                        <h5 class="m-b-5 font-size-18">Ảnh đại diện</h5>
                        <p class="opacity-07 font-size-13 m-b-0">
                            Đề xuất: <br>
                            Ảnh chi tiết
                        </p>
                    </div>
                    <div>
                        <label for="fphoto" class="btn btn-tone btn-primary">
                            <span>Chọn ảnh</span>
                            <input type="file" id="fphoto" name="fphoto" asp-for="Photo" onchange="previewAvatar(event)" style="display: none;">
                        </label>
                    </div>
                </div>

                <hr class="m-v-25">
                <div class="form-group">
                    <label class="font-weight-semibold" for="BicycleName">Tên xe đạp</label>
                    <input type="text" class="form-control" asp-for="BicycleName" autofocus>
                    @Html.ValidationMessage("BicycleName", new { @style = "color:#f00" })
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="LicensePlate">Biển số</label>
                        <input type="text" class="form-control" asp-for="LicensePlate">
                        @Html.ValidationMessage("LicensePlate", new { @style = "color:#f00" })
                    </div>
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="RentalPrice">Giá thuê</label>
                        <input type="number" class="form-control" asp-for="RentalPrice">
                        @Html.ValidationMessage("RentalPrice", new { @style = "color:#f00" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="ParkingId">Bãi xe</label>
                        <select class="custom-select" asp-for="ParkingId" style="min-width: 200px;" asp-items="ViewBag.lsBaiDo">
                            <option value="0" selected>Chọn bãi xe</option>
                        </select>
                        @Html.ValidationMessage("ParkingId", new { @style = "color:#f00" })
                    </div>
                    <div class="form-group col-md-6">
                        <label class="font-weight-semibold" for="BicycleStatusId">Trạng thái</label>
                        <select class="custom-select" asp-for="BicycleStatusId" style="min-width: 200px;" asp-items="ViewBag.lsTrangThai">
                            <option value="0" selected>Chọn trạng thái</option>
                        </select>
                        @Html.ValidationMessage("BicycleStatusId", new { @style = "color:#f00" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Mô tả</h4>
            </div>
            <div class="card-body">
                <textarea class="summernote" asp-for="Description"></textarea>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
            });
        });
        function previewAvatar(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('avatarPreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}

GreenMobility/Areas/Admin/Views/AdminBicycles/_BicycleTablePartial.cshtml
@model PagedList.Core.IPagedList<GreenMobility.Models.Bicycle>

@if (Model != null && Model.Count > 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Tên xe đạp</th>
                    <th scope="col">Biển số</th>
                    <th scope="col">Bãi đỗ</th>
                    <th scope="col">Trạng thái</th>
                    <th class="text-right" scope="col">Hành động</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.BicycleName</td>
                        <td>@item.LicensePlate</td>
                        <td>@item.Parking.ParkingName</td>
                        <td>@item.BicycleStatus.Description</td>
                        <td class="text-right">
                            <a class="btn btn-icon btn-hover btn-sm btn-rounded" asp-controller="AdminBicycles" asp-action="Edit" asp-route-id="@item.BicycleId">
                                <i class="anticon anticon-edit"></i>
                            </a>
                            <a class="btn btn-icon btn-hover btn-sm btn-rounded" asp-controller="AdminBicycles" asp-action="Details" asp-route-id="@item.BicycleId">
                                <i class="anticon anticon-eye"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-5">
            <ul class="pagination">
                <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminBicycles" asp-action="Search"></pager>
            </ul>
        </div>

        <div class="col-sm-12 col-md-7 text-right">
            <p>Tổng số xe: @Model.TotalItemCount</p>
        </div>
    </div>

}