GreenMobility/Areas/Admin/Controllers/AdminEmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GreenMobility.Models;
using PagedList.Core;
using AspNetCoreHero.ToastNotification.Abstractions;
using GreenMobility.Helper;
using Microsoft.AspNetCore.Authorization;

namespace GreenMobility.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminCookie",Roles = "Admin")]
    public class AdminEmployeesController : Controller
    {
        private readonly GreenMobilityContext _context;
        private readonly INotyfService _notyf;

        public AdminEmployeesController(GreenMobilityContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        // GET: Admin/AdminEmployees
        public async Task<IActionResult> Index(int page = 1, int status = 0, string keyword = "")
        {
            var pageNumber = page;
            var pageSize = 8;

            List<SelectListItem> lsStatus = new List<SelectListItem>();
            lsStatus.Add(new SelectListItem() { Text = "Tất cả trạng thái", Value = "0" });
            lsStatus.Add(new SelectListItem() { Text = "Hoạt động", Value = "1" });
            lsStatus.Add(new SelectListItem() { Text = "Khóa", Value = "2" });
            ViewData["lsStatus"] = lsStatus;

            IQueryable<Employee> employeeQuery = _context.Employees
                .AsNoTracking()
                .Include(x => x.Parking)
                .Where(x => x.IsDeleted == false);

            if (status == 1)
            {
                employeeQuery = employeeQuery.Where(x => x.IsWorking);
            }
            else if (status == 2)
            {
                employeeQuery = employeeQuery.Where(x => !x.IsWorking);
            }

            if (!string.IsNullOrEmpty(keyword))
            {
                keyword = keyword.Trim().ToLower();
                employeeQuery = employeeQuery.Where(x => x.FullName.ToLower().Contains(keyword) || x.Email.ToLower().Contains(keyword));
            }

            List<Employee> lsEmployees = await employeeQuery.ToListAsync();
            PagedList<Employee> models = new PagedList<Employee>(lsEmployees.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentStatus = status;
            ViewBag.Keyword = keyword;

            return View(models);
        }

        public IActionResult FilterAndSearch(int status = 0, string keyword = "")
        {
            var url = $"/Admin/AdminEmployees?status={status}&keyword={keyword}";
            if (status == 0 && string.IsNullOrEmpty(keyword))
            {
                url = "/Admin/AdminEmployees";
            }
            return Json(new { status = "success", redirectUrl = url });
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(m => m.Parking)
                .FirstOrDefaultAsync(m => m.EmployeeId == id && m.IsDeleted == false);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        public IActionResult Create()
        {
            ViewData["lsParkings"] = new SelectList(_context.Parkings, "ParkingId", "ParkingName");
            ViewData["lsRoles"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,FullName,BirthDate,Address,Phone,Email,Password,Photo,IsWorking,ParkingId,RoleId,IsDeleted")] Employee employee, IFormFile fPhoto)
        {
            if (string.IsNullOrWhiteSpace(employee.FullName))
                ModelState.AddModelError("FullName", "Họ và tên không được để trống");

            if (string.IsNullOrWhiteSpace(employee.Email))
                ModelState.AddModelError("Email", "Email không được để trống");

            if (string.IsNullOrWhiteSpace(employee.Phone))
                ModelState.AddModelError("Phone", "Số điện thoại không được để trống");

            if (string.IsNullOrWhiteSpace(employee.BirthDate.ToString()))
                ModelState.AddModelError("BirthDate", "Ngày sinh không được để trống");

            if (string.IsNullOrWhiteSpace(employee.Password))
                ModelState.AddModelError("Password", "Mật khẩu không được để trống");

            if (employee.ParkingId == 0)
                ModelState.AddModelError("ParkingId", "Vui lòng chọn bãi đỗ làm việc");

            if (employee.RoleId == 0)
                ModelState.AddModelError("RoleId", "Vui lòng chọn quyền truy cập");

            if (PhoneExists(employee.Phone))
                ModelState.AddModelError("Phone", "Số điện thoại đã tồn tại");

            if (EmailExists(employee.Email))
                ModelState.AddModelError("Email", "Email đã tồn tại");

            if (ModelState.IsValid)
            {
                employee.FullName = Utilities.ToTitleCase(employee.FullName);
                employee.Address = Utilities.ToTitleCase(employee.Address);
                if (fPhoto != null)
                {
                    string extension = Path.GetExtension(fPhoto.FileName);
                    string image = Utilities.SEOUrl(employee.FullName) + extension;
                    employee.Photo = await Utilities.UploadFile(fPhoto, @"employees", image.ToLower());
                }

                if (string.IsNullOrEmpty(employee.Photo)) employee.Photo = "default.jpg";
                employee.DateModified = DateTime.Now;
                employee.DateCreated = DateTime.Now;
                employee.IsWorking = true;
                employee.IsDeleted = false;

                _context.Add(employee);
                await _context.SaveChangesAsync();
                _notyf.Success("Tạo mới thành công");

                return RedirectToAction(nameof(Index));
            }
            _notyf.Error("Tạo mới thất bại, vui lòng kiểm tra lại thông tin");
            ViewData["lsParkings"] = new SelectList(_context.Parkings, "ParkingId", "ParkingName");
            ViewData["lsRoles"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            return View(employee);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FirstOrDefaultAsync(p => p.EmployeeId == id && p.IsDeleted == false);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["lsParkings"] = new SelectList(_context.Parkings, "ParkingId", "ParkingName");
            ViewData["lsRoles"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmployeeId,FullName,BirthDate,Address,Phone,Email,Password,Photo,IsWorking,ParkingId,RoleId,IsDeleted")] Employee employee, IFormFile fPhoto)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }
            if (string.IsNullOrWhiteSpace(employee.FullName))
                ModelState.AddModelError("FullName", "Họ và tên không được để trống");

            if (string.IsNullOrWhiteSpace(employee.Email))
                ModelState.AddModelError("Email", "Email không được để trống");

            if (string.IsNullOrWhiteSpace(employee.Phone))
                ModelState.AddModelError("Phone", "Số điện thoại không được để trống");

            if (string.IsNullOrWhiteSpace(employee.BirthDate.ToString()))
                ModelState.AddModelError("BirthDate", "Ngày sinh không được để trống");

            if (string.IsNullOrWhiteSpace(employee.Password))
                ModelState.AddModelError("Password", "Mật khẩu không được để trống");

            if (employee.ParkingId == 0)
                ModelState.AddModelError("ParkingId", "Vui lòng chọn bãi đỗ làm việc");

            if (employee.RoleId == 0)
                ModelState.AddModelError("RoleId", "Vui lòng chọn quyền truy cập");

            if (PhoneExistsExceptCurrent(employee.Phone, id))
                ModelState.AddModelError("Phone", "Số điện thoại đã tồn tại");

            if (EmailExistsExceptCurrent(employee.Email, id))
                ModelState.AddModelError("Email", "Email đã tồn tại");

            if (ModelState.IsValid)
            {  
                try
                {
                        employee.FullName = Utilities.ToTitleCase(employee.FullName);
                        employee.Address = Utilities.ToTitleCase(employee.Address);
                        if (fPhoto != null)
                        {
                            string extension = Path.GetExtension(fPhoto.FileName);
                            string image = Utilities.SEOUrl(employee.FullName) + extension;
                            employee.Photo = await Utilities.UploadFile(fPhoto, @"employees", image.ToLower());
                        }

                        if (string.IsNullOrEmpty(employee.Photo)) employee.Photo = "default.jpg";
                        employee.DateModified = DateTime.Now;

                        _context.Update(employee);
                        await _context.SaveChangesAsync();
                        _notyf.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))

GreenMobility/Areas/Admin/Views/AdminEmployees/Create.cshtml
@model GreenMobility.Models.Employee

@{
    ViewData["Title"] = "Thêm mới nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminEmployees" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters">
        <div class="row align-items-md-center">
            <div class="col-md-8">
                <h2 class="header-title">Quản lý nhân viên</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                        <a asp-area="Admin" asp-controller="AdminEmployees" asp-action="Index" class="breadcrumb-item">Danh sách nhân viên</a>
                        <span class="breadcrumb-item active">Thêm mới nhân viên</span>
                    </nav>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-md-right">
                    <div>
                        <button type="submit" class="btn btn-primary mr-1">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        <a asp-area="Admin" asp-controller="AdminEmployees" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="tab-account">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông tin cơ bản</h4>
                </div>
                <div class="card-body">
                    <div class="media align-items-center">
                        <div class="avatar avatar-image m-h-10 m-r-15" style="height: 80px; width: 80px">
                            <img id="avatarPreview" src="~/images/employees/default.jpg" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                        </div>

                        <div class="m-l-20 m-r-20">
                            <h5 class="m-b-5 font-size-18">Ảnh đại diện</h5>
                            <p class="opacity-07 font-size-13 m-b-0">
                                Đề xuất: <br>
                                1x1 Ảnh rõ mặt
                            </p>
                        </div>
                        <div>
                            <label for="Photo" class="btn btn-tone btn-primary">Chọn ảnh</label>
                            <input type="file" name="fphoto" asp-for="Photo" onchange="previewAvatar(event)" style="display: none;">
                        </div>
                    </div>

                    <hr class="m-v-25">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="FullName">Họ và tên:</label>
                            <input type="text" class="form-control" asp-for="FullName" placeholder="Họ và tên">
                            @Html.ValidationMessage("FullName", "", new { @style = "color:#f00" })
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="Email">Email:</label>
                            <input type="email" class="form-control" asp-for="Email" placeholder="email">
                            @Html.ValidationMessage("Email", "", new { @style = "color:#f00" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="Phone">Số điện thoại:</label>
                            <input type="text" class="form-control" asp-for="Phone" placeholder="Số điện thoại">
                            @Html.ValidationMessage("Phone", "", new { @style = "color:#f00" })
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="BirthDate">Ngày sinh:</label>
                            <input type="date" class="form-control" asp-for="BirthDate" placeholder="Ngày sinh">
                            @Html.ValidationMessage("BirthDate", "", new { @style = "color:#f00" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="font-weight-semibold" for="Address">Địa chỉ:</label>
                            <input type="text" class="form-control" asp-for="Address" placeholder="Địa chỉ">
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Mật khẩu</h4>
                </div>
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="font-weight-semibold" for="Password">Mật khẩu:</label>
                            <input type="password" class="form-control" asp-for="Password" placeholder="Mật khẩu">
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông tin công việc</h4>
                </div>
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="font-weight-semibold" for="RoleId">Quyền truy cập</label>
                            <select class="custom-select" asp-for="RoleId" style="min-width: 200px;" asp-items="ViewBag.lsRoles">
                                <option value="0" selected>Chọn quyền truy cập</option>
                            </select>
                            @Html.ValidationMessage("RoleId", new { @style = "color:#f00" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="font-weight-semibold" for="ParkingId">Bãi đỗ</label>
                            <select class="custom-select" asp-for="ParkingId" style="min-width: 200px;" asp-items="ViewBag.lsParkings">
                                <option value="0" selected>Chọn bãi đỗ</option>
                            </select>
                            @Html.ValidationMessage("ParkingId", new { @style = "color:#f00" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <script>
        function previewAvatar(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('avatarPreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}

GreenMobility/Areas/Admin/Views/AdminEmployees/Details.cshtml
@model GreenMobility.Models.Employee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header no-gutters">
    <div class="row align-items-md-center">
        <div class="col-md-7">
            <h2 class="header-title">Quản lý nhân viên</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                    <a asp-area="Admin" asp-controller="AdminEmployees" asp-action="Index" class="breadcrumb-item">Danh sách nhân viên</a>
                    <span class="breadcrumb-item active">Chi tiết nhân viên</span>
                </nav>
            </div>
        </div>
        <div class="col-md-5">
            <div class="text-md-right d-flex justify-content-end">
                <div class="d-flex align-items-center">
                    <a class="btn btn-primary btn-tone mr-2" asp-area="Admin" asp-controller="AdminEmployees" asp-action="Edit" asp-route-id="@Model.EmployeeId">Sửa đổi</a>
                    <form id="deleteForm" method="post" asp-action="Delete" asp-route-id="@Model.EmployeeId" class="mr-2">
                        <button type="submit" class="btn btn-danger btn-tone">Xóa</button>
                    </form>
                    <a asp-area="Admin" asp-controller="AdminEmployees" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-md-7">
                <div class="d-md-flex align-items-center">
                    <div class="text-center text-sm-left ">
                        <div class="avatar avatar-image" style="width: 150px; height:150px">
                            <img src="~/images/employees/@Model.Photo" alt="@Model.FullName">
                        </div>
                    </div>
                    <div class="text-center text-sm-left m-v-15 p-l-30">
                        <h2 class="m-b-5">@Model.FullName</h2>
                        <p class="text-opacity font-size-13">@Model.BirthDate?.ToString("dd/MM/yyyy")</p>
                        <p class="text-dark m-b-20">
                            @if ((bool)Model.IsWorking)
                            {
                                <div class="d-flex align-items-center">
                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                    <div>Làm việc</div>
                                </div>
                            }
                            else
                            {
                                <div class="d-flex align-items-center">
                                    <div class="badge badge-danger badge-dot m-r-10"></div>
                                    <div>Nghỉ</div>
                                </div>
                            }
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="d-md-block d-none border-left col-1"></div>
                    <div class="col">
                        <ul class="list-unstyled m-t-10">
                            <li class="row">
                                <p class="col-sm-4 col-4 font-weight-semibold text-dark m-b-5">
                                    <i class="m-r-10 text-primary anticon anticon-mail"></i>
                                    <span>Email: </span>
                                </p>
                                <p class="col font-weight-semibold"> @Model.Email</p>
                            </li>
                            <li class="row">
                                <p class="col-sm-4 col-4 font-weight-semibold text-dark m-b-5">
                                    <i class="m-r-10 text-primary anticon anticon-phone"></i>
                                    <span>Phone: </span>
                                </p>
                                <p class="col font-weight-semibold"> @Model.Phone</p>
                            </li>
                            <li class="row">
                                <p class="col-sm-4 col-5 font-weight-semibold text-dark m-b-5">
                                    <i class="m-r-10 text-primary anticon anticon-compass"></i>
                                    <span>Location: </span>
                                </p>
                                <p class="col font-weight-semibold"> @Model.Address</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Thông tin làm việc</h4>
                <div class="table-responsive">
                    <table class="product-info-table m-t-20">
                        <tbody>
                            <tr>
                                <td>Ngày bắt đầu làm việc:</td>
                                <td class="text-dark font-weight-semibold">@Model.DateCreated?.ToString("dd/MM/yyyy")</td>
                            </tr>
                            <tr>
                                <td>Làm việc tại:</td>
                                <td>@Model.Parking.ParkingName</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById("deleteForm").addEventListener("submit", function (event) {
        event.preventDefault();

        if (confirm("Bạn có chắc chắn muốn xóa nhân viên này?")) {
            this.submit();
        }
    });
</script>

GreenMobility/Areas/Admin/Views/AdminEmployees/Edit.cshtml
@model GreenMobility.Models.Employee

@{
    ViewData["Title"] = "Chỉnh sửa nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-controller="AdminEmployees" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="EmployeeId" />
    <input type="hidden" asp-for="Photo" />
    <input type="hidden" asp-for="Password" />
    <input type="hidden" asp-for="IsDeleted" />
    <input type="hidden" asp-for="DateCreated" />
    <div class="page-header no-gutters">
        <div class="row align-items-md-center">
            <div class="col-md-8">
                <h2 class="header-title">Quản lý nhân viên</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                        <a asp-area="Admin" asp-controller="AdminEmployees" asp-action="Index" class="breadcrumb-item">Danh sách nhân viên</a>
                        <span class="breadcrumb-item active">Chỉnh sửa nhân viên</span>
                    </nav>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-md-right">
                    <div>
                        <button type="submit" class="btn btn-primary mr-1">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        <a asp-area="Admin" asp-controller="AdminEmployees" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="tab-account">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông tin cơ bản</h4>
                </div>
                <div class="card-body">
                    <div class="media align-items-center">
                        <div class="avatar avatar-image m-h-10 m-r-15" style="height: 80px; width: 80px">
                            <img id="avatarPreview" src="~/images/employees/@Model.Photo" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                        </div>

                        <div class="m-l-20 m-r-20">
                            <h5 class="m-b-5 font-size-18">Ảnh đại diện</h5>
                            <p class="opacity-07 font-size-13 m-b-0">
                                Đề xuất: <br>
                                1x1 Ảnh rõ mặt
                            </p>
                        </div>
                        <div>
                            <label for="fphoto" class="btn btn-tone btn-primary">
                                <span>Chọn ảnh</span>
                                <input type="file" id="fphoto" name="fphoto" asp-for="Photo" onchange="previewAvatar(event)" style="display: none;">
                            </label>
                        </div>
                    </div>

                    <hr class="m-v-25">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="FullName">Họ và tên:</label>
                            <input type="text" class="form-control" asp-for="FullName" placeholder="Họ và tên">
                            @Html.ValidationMessage("FullName", "", new { @style = "color:#f00" })
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="Email">Email:</label>
                            <input type="email" class="form-control" asp-for="Email" placeholder="email">
                            @Html.ValidationMessage("Email", "", new { @style = "color:#f00" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="Phone">Số điện thoại:</label>
                            <input type="text" class="form-control" asp-for="Phone" placeholder="Số điện thoại">
                            @Html.ValidationMessage("Phone", "", new { @style = "color:#f00" })
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="BirthDate">Ngày sinh:</label>
                            <input type="date" class="form-control" asp-for="BirthDate" placeholder="Ngày sinh">
                            @Html.ValidationMessage("BirthDate", "", new { @style = "color:#f00" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="font-weight-semibold" for="Address">Địa chỉ:</label>
                            <input type="text" class="form-control" asp-for="Address" placeholder="Địa chỉ">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="IsWorking">
                            <label for="IsWorking"></label>
                        </div>
                        <label>Làm việc</label>
                    </div>
                    @Html.ValidationMessage("Error", "", new { @style = "color:#f00" })
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông tin công việc</h4>
                </div>
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="font-weight-semibold" for="RoleId">Quyền truy cập</label>
                            <select class="custom-select" asp-for="RoleId" style="min-width: 200px;" asp-items="ViewBag.lsRoles">
                                <option value="0" selected>Chọn quyền truy cập</option>
                            </select>
                            @Html.ValidationMessage("RoleId", new { @style = "color:#f00" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="font-weight-semibold" for="ParkingId">Bãi đỗ</label>
                            <select class="custom-select" asp-for="ParkingId" style="min-width: 200px;" asp-items="ViewBag.lsParkings">
                                <option value="0" selected>Chọn bãi đỗ</option>
                            </select>
                            @Html.ValidationMessage("ParkingId", new { @style = "color:#f00" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <script>
        function previewAvatar(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('avatarPreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}