GreenMobility/Areas/Admin/Controllers/AdminParkingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GreenMobility.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using GreenMobility.Helper;
using Microsoft.AspNetCore.Authorization;

namespace GreenMobility.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class AdminParkingsController : Controller
    {
        private readonly GreenMobilityContext _context;
        private readonly INotyfService _notyf;
        public AdminParkingsController(GreenMobilityContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }
        public async Task<IActionResult> Index(int page = 1, int isActive = 0, string keyword = "")
        {
            var pageNumber = page;
            var pageSize = 20;

            List<SelectListItem> lsStatus = new List<SelectListItem>();
            lsStatus.Add(new SelectListItem() { Text = "Tất cả trạng thái", Value = "0" });
            lsStatus.Add(new SelectListItem() { Text = "Hoạt động", Value = "1" });
            lsStatus.Add(new SelectListItem() { Text = "Khóa", Value = "2" });
            ViewData["lsStatus"] = lsStatus;

            IQueryable<Parking> parkingQuery = _context.Parkings
                .AsNoTracking()
                .Where(x => x.IsDeleted == false);

            if (isActive == 1)
            {
                parkingQuery = parkingQuery.Where(x => x.IsActive);
            }
            else if (isActive == 2)
            {
                parkingQuery = parkingQuery.Where(x => !x.IsActive);
            }

            if (!string.IsNullOrEmpty(keyword))
            {
                keyword = keyword.Trim().ToLower();
                parkingQuery = parkingQuery.Where(x => x.ParkingName.ToLower().Contains(keyword) || x.Address.ToLower().Contains(keyword));
            }

            List<Parking> lsParkings = await parkingQuery.ToListAsync();
            PagedList<Parking> models = new PagedList<Parking>(lsParkings.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentActive = isActive;
            ViewBag.Keyword = keyword;

            return View(models);
        }
        public IActionResult FilterAndSearch(int isActive = 0, string keyword = "")
        {
            var url = $"/Admin/AdminParkings?isActive={isActive}&keyword={keyword}";
            if (isActive == 0 && string.IsNullOrEmpty(keyword))
            {
                url = "/Admin/AdminParkings";
            }
            return Json(new { status = "success", redirectUrl = url });
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Parkings == null)
            {
                return NotFound();
            }

            var parking = await _context.Parkings
                .FirstOrDefaultAsync(m => m.ParkingId == id && m.IsDeleted == false);
            if (parking == null)
            {
                return NotFound();
            }

            return View(parking);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ParkingId,ParkingName,Address,IsActive,Photo,IsDeleted")] Parking parking, IFormFile? fPhoto)
        {
            if (string.IsNullOrWhiteSpace(parking.ParkingName))
                ModelState.AddModelError("ParkingName", "Tên bãi đỗ không được để trống");

            if (string.IsNullOrWhiteSpace(parking.Address))
                ModelState.AddModelError("Address", "Địa chỉ không được để trống");

            if (ParkingNameExists(parking.ParkingName))
                ModelState.AddModelError("ParkingName", "Tên bãi đỗ đã tồn tại");

            if (ModelState.IsValid)
            {
                parking.ParkingName = Utilities.ToTitleCase(parking.ParkingName);
                {
                    if (fPhoto != null)
                    {
                        string extension = Path.GetExtension(fPhoto.FileName);
                        string image = Utilities.SEOUrl(parking.ParkingName) + extension;
                        parking.Photo = await Utilities.UploadFile(fPhoto, @"parkings", image.ToLower());
                    }
                }

                if (string.IsNullOrEmpty(parking.Photo)) parking.Photo = "default.jpg";

                parking.Alias = Utilities.SEOUrl(parking.ParkingName);
                parking.DateModified = DateTime.Now;
                parking.DateCreated = DateTime.Now;
                parking.IsDeleted = false;

                _context.Add(parking);
                await _context.SaveChangesAsync();
                _notyf.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }
            _notyf.Error("Tạo mới thất bại, vui lòng kiểm tra lại thông tin");
            return View(parking);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Parkings == null)
            {
                return NotFound();
            }
            var parking = await _context.Parkings.FirstOrDefaultAsync(p => p.ParkingId == id && p.IsDeleted == false);
            if (parking == null)
            {
                return NotFound();
            }
            return View(parking);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ParkingId,ParkingName,Address,IsActive,Photo,IsDeleted")] Parking parking, IFormFile? fPhoto)
        {
            if (id != parking.ParkingId)
            {
                return NotFound();
            }

            if (string.IsNullOrWhiteSpace(parking.ParkingName))
                ModelState.AddModelError("ParkingName", "Tên bãi đỗ không được để trống");

            if (string.IsNullOrWhiteSpace(parking.Address))
                ModelState.AddModelError("Address", "Địa chỉ không được để trống");

            if (ParkingNameExistsExceptCurrent(parking.ParkingName, id))
                ModelState.AddModelError("ParkingName", "Tên bãi đỗ đã tồn tại");

            if (ModelState.IsValid)
            {
                try
                {
                    parking.ParkingName = Utilities.ToTitleCase(parking.ParkingName);
                    {
                        if (fPhoto != null)
                        {
                            string extension = Path.GetExtension(fPhoto.FileName);
                            string image = Utilities.SEOUrl(parking.ParkingName) + extension;
                            parking.Photo = await Utilities.UploadFile(fPhoto, @"parkings", image.ToLower());
                        }
                    }
                    if (string.IsNullOrEmpty(parking.Photo)) parking.Photo = "default.jpg";

                    parking.Alias = Utilities.SEOUrl(parking.ParkingName);
                    parking.DateModified = DateTime.Now;

                    _context.Update(parking);
                    await _context.SaveChangesAsync();
                    _notyf.Success("Cập nhật bãi đỗ thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParkingExists(parking.ParkingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            _notyf.Error("Chỉnh sửa thất bại, vui lòng kiểm tra lại thông tin");
            return View(parking);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var bicycles = await _context.Bicycles.Where(b => b.ParkingId == id).ToListAsync();
                foreach (var bicycle in bicycles)
                {
                    bicycle.ParkingId = 2066;
                    bicycle.BicycleStatusId = 4;
                    _context.Update(bicycle);
                }
                await _context.SaveChangesAsync();

                var parking = await _context.Parkings.FindAsync(id);
                if (parking == null)
                {
                    return NotFound();
                }

                parking.IsDeleted = true;
                _context.Update(parking);
                await _context.SaveChangesAsync();

                _notyf.Success("Xóa bãi đỗ thành công");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _notyf.Error("Xóa bãi đỗ thất bại");
                return RedirectToAction(nameof(Index));
            }
        }

        private bool ParkingExists(int id)
        {
            return (_context.Parkings?.Any(e => e.ParkingId == id)).GetValueOrDefault();
        }

        private bool ParkingNameExists(string parkingName)
        {
            return _context.Parkings.Any(p => p.ParkingName == parkingName);
        }

        private bool ParkingNameExistsExceptCurrent(string parkingName, int id)
        {
            return _context.Parkings.Any(p => p.ParkingName == parkingName && p.ParkingId != id);
        }
    }
}

GreenMobility/Areas/Admin/Views/AdminParkings/Create.cshtml
@model GreenMobility.Models.Parking

@{
    ViewData["Title"] = "Thêm mới bãi đỗ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-controller="AdminParkings" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters">
        <div class="row align-items-md-center">
            <div class="col-md-8">
                <h2 class="header-title">Quản lý bãi đỗ</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                        <a asp-area="Admin" asp-controller="AdminParkings" asp-action="Index" class="breadcrumb-item">Danh sách bãi đỗ</a>
                        <span class="breadcrumb-item active">Thêm mới bãi đỗ</span>
                    </nav>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-md-right">
                    <div>
                        <button type="submit" class="btn btn-primary mr-1">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        <a asp-area="Admin" asp-controller="AdminPosts" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-content m-t-15">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Thông tin bãi đỗ</h4>
            </div>
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="img-fluid m-h-10 m-r-15" style="height: 80px; width: 120px">
                        <img id="avatarPreview" src="~/images/parkings/default.jpg" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                    </div>

                    <div class="m-l-20 m-r-20">
                        <h5 class="m-b-5 font-size-18">Ảnh đại diện</h5>
                        <p class="opacity-07 font-size-13 m-b-0">
                            Đề xuất: <br>
                            Ảnh chi tiết
                        </p>
                    </div>
                    <div>
                        <label for="Photo" class="btn btn-tone btn-primary">Chọn ảnh</label>
                        <input type="file" name="fPhoto" asp-for="Photo" onchange="previewAvatar(event)" style="display: none;">
                    </div>
                </div>

                <hr class="m-v-25">
                <div class="form-group">
                    <label class="font-weight-semibold" for="ParkingName">Tên bãi đỗ</label>
                    <input type="text" class="form-control" asp-for="ParkingName" name="ParkingName">
                    @Html.ValidationMessage("ParkingName", "",new { @style = "color:#f00" })
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold" for="Address">Địa chỉ</label>
                    <input type="text" class="form-control" asp-for="Address">
                    @Html.ValidationMessage("Address", "", new { @style = "color:#f00" })
                </div>
                <div class="form-group d-flex align-items-center">
                    <div class="switch m-r-10">
                        <input type="checkbox" asp-for="IsActive">
                        <label for="IsActive"></label>
                    </div>
                    <label>Hoạt động</label>
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <script>
        function previewAvatar(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('avatarPreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}

GreenMobility/Areas/Admin/Views/AdminParkings/Details.cshtml
@model GreenMobility.Models.Parking

@{
    ViewData["Title"] = "Thông tin bãi đỗ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header no-gutters">
    <div class="row align-items-md-center">
        <div class="col-md-7">
            <h2 class="header-title">Quản lý bãi đỗ</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                    <a asp-area="Admin" asp-controller="AdminParkings" asp-action="Index" class="breadcrumb-item">Danh sách bãi đỗ</a>
                    <span class="breadcrumb-item active">Thông tin bãi đỗ</span>
                </nav>
            </div>
        </div>
        <div class="col-md-5">
            <div class="text-md-right d-flex justify-content-end">
                <div class="d-flex align-items-center">
                    <a class="btn btn-primary btn-tone mr-2" asp-area="Admin" asp-controller="AdminParkings" asp-action="Edit" asp-route-id="@Model.ParkingId">Sửa đổi</a>
                    <form id="deleteForm" method="post" asp-action="Delete" asp-route-id="@Model.ParkingId" class="mr-2">
                        <button type="submit" class="btn btn-danger btn-tone">Xóa</button>
                    </form>
                    <a asp-area="Admin" asp-controller="AdminParkings" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="tab-content m-t-15">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Thông tin bãi đỗ</h4>
        </div>
        <div class="card-body">
            <div class="media align-items-center">
                <div class="img-fluid m-h-10 m-r-15" style="height: 80px; width: 120px">
                    <img id="avatarPreview" src="~/images/parkings/@Model.Photo" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                </div>

                <div class="m-l-20 m-r-20">
                    <h5 class="m-b-5 font-size-18">@Model.ParkingName - @Model.Address</h5>
                </div>
            </div>
            <hr class="m-v-25">
            <div class="table-responsive">
                <table class="product-info-table">
                    <tbody>
                        <tr>
                            <td>Tên bãi đỗ:</td>
                            <td class="text-dark font-weight-semibold">@Model.ParkingName</td>
                        </tr>
                        <tr>
                            <td>Alias:</td>
                            <td>@Model.Alias</td>
                        </tr>
                        <tr>
                            <td>Địa chỉ:</td>
                            <td>@Model.Address</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById("deleteForm").addEventListener("submit", function (event) {
        event.preventDefault();

        if (confirm("Bạn có chắc chắn muốn xóa bãi đỗ này?")) {
            this.submit();
        }
    });
</script>

GreenMobility/Areas/Admin/Views/AdminParkings/Edit.cshtml
@model GreenMobility.Models.Parking

@{
    ViewData["Title"] = "Chỉnh sửa bãi đỗ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-controller="AdminParkings" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ParkingId" />
    <input type="hidden" asp-for="Photo" />
    <input type="hidden" asp-for="DateCreated" />
    <input type="hidden" asp-for="IsDeleted" />
    <div class="page-header no-gutters">
        <div class="row align-items-md-center">
            <div class="col-md-8">
                <h2 class="header-title">Quản lý bãi đỗ</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                        <a asp-area="Admin" asp-controller="AdminParkings" asp-action="Index" class="breadcrumb-item">Danh sách bãi đỗ</a>
                        <span class="breadcrumb-item active">Chỉnh sửa bãi đỗ</span>
                    </nav>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-md-right">
                    <div>
                        <button type="submit" class="btn btn-primary mr-1">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        <a asp-area="Admin" asp-controller="AdminParkings" asp-action="Index" class="btn btn-success btn-tone">Quay lại</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-content m-t-15">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Thông tin bãi đỗ</h4>
            </div>
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="img-fluid m-h-10 m-r-15" style="height: 80px; width: 120px">
                        <img id="avatarPreview" src="~/images/parkings/@Model.Photo" alt="Avatar Preview" style="object-fit: contain; width: 100%; height: 100%;">
                    </div>

                    <div class="m-l-20 m-r-20">
                        <h5 class="m-b-5 font-size-18">Ảnh đại diện</h5>
                        <p class="opacity-07 font-size-13 m-b-0">
                            Đề xuất: <br>
                            Ảnh chi tiết
                        </p>
                    </div>
                    <div>
                        <label for="fphoto" class="btn btn-tone btn-primary">
                            <span>Chọn ảnh</span>
                            <input type="file" id="fphoto" name="fphoto" asp-for="Photo" onchange="previewAvatar(event)" style="display: none;">
                        </label>
                    </div>
                </div>

                <hr class="m-v-25">
                <div class="form-group">
                    <label class="font-weight-semibold" for="ParkingName">Tên bãi đỗ</label>
                    <input type="text" class="form-control" asp-for="ParkingName" name="ParkingName">
                    @Html.ValidationMessage("ParkingName", "", new { @style = "color:#f00" })
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold" for="Address">Địa chỉ</label>
                    <input type="text" class="form-control" asp-for="Address">
                    @Html.ValidationMessage("Address", "", new { @style = "color:#f00" })
                </div>
                <div class="form-group d-flex align-items-center">
                    <div class="switch m-r-10">
                        <input type="checkbox" asp-for="IsActive">
                        <label for="IsActive"></label>
                    </div>
                    <label>Hoạt động</label>
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <script>
        function previewAvatar(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('avatarPreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
}

GreenMobility/Areas/Admin/Views/AdminParkings/Index.cshtml
@using PagedList.Core.Mvc;
@model PagedList.Core.IPagedList<GreenMobility.Models.Parking>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Quản lý bãi đỗ: page " + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header no-gutters">
    <div class="row align-items-md-center">
        <div class="col-md-8">
            <h2 class="header-title">Quản lý bãi đỗ</h2>
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                <span class="breadcrumb-item active">Danh sách bãi đỗ : Trang @CurrentPage</span>
            </nav>
        </div>
        <div class="col-md-4">
            <div class="text-md-right">
                <div>
                    <a class="btn btn-primary" asp-controller="AdminParkings" asp-action="Create">
                        <i class="anticon anticon-plus-circle m-r-5"></i>
                        <span>Thêm mới bãi đỗ</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-10">
                        <div class="input-affix m-v-4">
                            <i class="prefix-icon anticon anticon-search opacity-04"></i>
                            <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm kiếm">
                        </div>
                    </div>
                    <div class="d-md-flex">
                        <div class="m-b-10">
                            <select class="custom-select" id="idstatus" name="idstatus" style="min-width: 180px;" asp-items="ViewBag.lsStatus">
                                <option value="" disabled selected>Chọn trạng thái</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Tên bãi đỗ</th>
                        <th scope="col">Địa chỉ</th>
                        <th scope="col">Trạng thái</th>
                        <th class="text-right" scope="col">Hành động</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Count > 0)
                    {
                        int OrdinalNumber = (CurrentPage - 1) * Model.PageSize;
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@(++OrdinalNumber)</td>
                                <td><a asp-controller="AdminParkings" asp-action="Details" asp-route-id="@item.ParkingId">@item.ParkingName</a></td>
                                <td>@item.Address</td>
                                <td>
                                    @if ((bool)item.IsActive)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Hoạt động</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-danger badge-dot m-r-10"></div>
                                            <div>Khóa</div>
                                        </div>
                                    }
                                </td>
                                <td class="text-right">
                                    <a class="btn btn-icon btn-hover btn-sm btn-rounded" asp-controller="AdminParkings" asp-action="Edit" asp-route-id="@item.ParkingId">
                                        <i class="anticon anticon-edit"></i>
                                    </a>
                                    <form class="deleteForm" method="post" asp-controller="AdminParkings" asp-action="Delete" asp-route-id="@item.ParkingId" style="display:inline-block;">
                                        <button type="submit" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-delete"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="6" class="text-left">Chưa có dữ liệu</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        @if (Model != null && Model.Count > 0)
        {
            <div class="row">
                <div class="col-sm-12 col-md-5">
                    <ul class="pagination">
                        <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminParkings" asp-route-isActive="@ViewBag.CurrentActive" asp-route-keyword="@ViewBag.Keyword" asp-action="Index"></pager>
                    </ul>
                </div>
                <div class="col-sm-12 col-md-7 text-right">
                    <p>Đang xem @Model.FirstItemOnPage đến @Model.LastItemOnPage trong tổng số @Model.TotalItemCount mục</p>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#idstatus, #keyword").change(function () {
                var isActive = $("#idstatus").children(":selected").val();
                var keyword = $("#keyword").val();
                isActive = parseFloat(isActive);
                $('#idstatus option').removeAttr('selected');
                $("#idstatus > [value = " + isActive + "]").attr("selected", true);
                $.ajax({
                    url: '/Admin/AdminParkings/FilterAndSearch',
                    dataType: "json",
                    type: 'GET',
                    data: { isActive: isActive, keyword: keyword },
                    success: function (response) {
                        if (response.status === "success") {
                            window.location.href = response.redirectUrl;
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            });
        });
        $(function () {
            var isActive = @ViewBag.CurrentActive;
            $("#idstatus").val(isActive);
            var keyword = "@ViewBag.Keyword";
            $("#keyword").val(keyword);
        });
        $('.deleteForm').on('submit', function (event) {
            event.preventDefault();
            if (confirm("Bạn có chắc chắn muốn xóa bãi đỗ này?")) {
                this.submit();
            }
        });
    </script>
}